### ISSUE TITLE
Hintergrundfarbe Kategorientags

### ISSUE THREAD

**Issue by patrickschiffer** [Piratenpartei/Pirate-Rogue#1]
Farbton: #672082

**Comment by xwolfde** [comment]
Hm. also im Slider gefällt mir 
![screenshot-cats-lila](https://cloud.githubusercontent.com/assets/1070669/23572705/413d87ea-0071-11e7-80a4-ebbd71094877.jpg)
ehrlich gesagt das Orange besser


Zum Vergleich
![screenshot-menu-color-default](https://cloud.githubusercontent.com/assets/1070669/23572712/535a4be8-0071-11e7-9efa-f0b850a614f6.jpg)

**Comment by patrickschiffer** [comment]
Ich finde violett besser lesbar. Und es gibt der Seite mehr Abwechslung.

**Comment by xwolfde** [comment]
im nächsten update drin
