### ISSUE TITLE
Darstellungsfehler im Menü

### ISSUE THREAD

**Issue by JanRei** [Piratenpartei/Pirate-Rogue#109]
Ist kein Menü konfiguriert, fehlen sowohl im Hautmenü als auch im Overlay-Menü die Seitentitel:
![image](https://cloud.githubusercontent.com/assets/2790261/25849320/5018a9e4-34be-11e7-8cc6-39895fcc4989.png)

Außerdem werden folgende PHP-Hinweise protokolliert:
> Trying to get property of non-object in wp-content\themes\Pirate-Rogue\inc\template-functions.php on line 249
> Trying to get property of non-object in wp-content\themes\Pirate-Rogue\inc\template-functions.php on line 251
> Trying to get property of non-object in wp-content\themes\Pirate-Rogue\inc\template-functions.php on line 253
> Trying to get property of non-object in wp-content\themes\Pirate-Rogue\inc\template-functions.php on line 255
> Trying to get property of non-object in wp-content\themes\Pirate-Rogue\inc\template-functions.php on line 303
> Trying to get property of non-object in wp-content\themes\Pirate-Rogue\inc\template-functions.php on line 305
> Trying to get property of non-object in wp-content\themes\Pirate-Rogue\inc\template-functions.php on line 307
> Trying to get property of non-object in wp-content\themes\Pirate-Rogue\inc\template-functions.php on line 309

Version: 1.0.51

**Comment by xwolfde** [comment]
fixed im nächsten release
