### ISSUE TITLE
PHP-Hinweis, wenn keine Beiträge vorhanden

### ISSUE THREAD

**Issue by JanRei** [Piratenpartei/Pirate-Rogue#130]
Wenn ich alle Beiträge lösche, erscheint in der Seitenleiste folgender Hinweis:

> Notice:  Trying to get property of non-object in wordpress\wp-content\themes\Pirate-Rogue\sidebar.php on line 15

Version: 1.0.56

**Comment by xwolfde** [comment]
wohl schon behoben in 1.1.x
