### ISSUE TITLE
Theme auf wordpress.org

### ISSUE THREAD

**Issue by ukcb** [Piratenpartei/Pirate-Rogue#131]
Planst du das Theme auf https://wordpress.org/themes/ zu legen? Würde Updates sehr einfach machen.

**Comment by xwolfde** [comment]
Ja. Ich möchte es aber erst noch von ein paar Workarounds befreien, die ich wegen dem Zeitdruck machen musste.
Kommt.
Kann nur noch nicht sagen wann.

**Comment by xwolfde** [comment]
würde doch zu viel aufwand kosten. Wer will soll lieber das plugin installieren, welches die Themes aus Git updated. Das  funktioniert
