### ISSUE TITLE
Section About

### ISSUE THREAD

**Issue by ukcb** [Piratenpartei/Pirate-Rogue#135]
Die "Section About" klebt über Section 4-spaltig und Section 6-spaltig, das passt da nicht wirklich.
Der Sinn von "Section auf Hintergrund" erschließt sich mir nicht, die Kategorien überlagern dort den Titel.

[Testseite](https://testing.piratenbrandenburg.de/)

**Comment by xwolfde** [comment]
"Section auf Hintergrund" wirkt erst dann sinnvoll, wenn du Artikel mit Artikelbild hast; Und davon mehr als 4. Jeder vierte Artikel in der Blogroll erhält dann in der Lilste das Hintergrundbild als breite Überlagerung.
Das macht nur dann Sinn zu nutzen, wenn die Artikel wirklich mit sauberen Artikelbilder gepflegt sind.

Die Positionen sind leider noch fest in der Blogroll. Alternativ kann man aber mit den Section Shortcodes sich eine eigene Blogroll auf einer Seite anlegen und dort eine eigene Reihenfolge bestimmen.
