### ISSUE TITLE
Kommafehler im Hamburgermenü.

### ISSUE THREAD

**Issue by sebulino** [Piratenpartei/Pirate-Rogue#142]
"Weck die Regierung auf!
Mit deiner Unterschrift ermöglichst du uns an der Bundestagswahl teilzunehmen. Klick hier!"
muss zu 
"... ermöglichst du uns, an der ..."

**Comment by xwolfde** [comment]
fixed. muss aber trotzdem noch anders. (Anfängertext: "Klick hier")
