### ISSUE TITLE
falsches orange in Piratenlogo im Head

### ISSUE THREAD

**Issue by sebulino** [Piratenpartei/Pirate-Rogue#143]
Im Logo ist der orangene Kreis mit der Fahne drin in einem F39200,
alle anderen Oranges (Buttons, Hovers, Linien, Icons, ...) waren auf den ersten Blick ein FF8800.

<img width="397" alt="bildschirmfoto 2017-05-31 um 21 50 13" src="https://cloud.githubusercontent.com/assets/1427176/26651563/652fbe08-464d-11e7-9944-b534ef362639.png">

**Comment by xwolfde** [comment]
@patrickschiffer Stimmt... Bei Konvertieren passiert?

**Comment by patrickschiffer** [comment]
Ja, womöglich. Ich gehe mal meine Vorlagen durch und passe es an.

**Comment by xwolfde** [comment]
Auf Website; Nicht Teil des Themes
