### ISSUE TITLE
Social Media Icons führen von der Webseite weg

### ISSUE THREAD

**Issue by sebulino** [Piratenpartei/Pirate-Rogue#144]
Der Klick auf die Social Media icons öffnet kein eigenes Fenster, sondern führt den geneigten Leser wieder von unserer Seite weg (Safari, Version am 31.5. um 22:00).

**Comment by xwolfde** [comment]
Genau.  Ist Absicht. Links in neuen tabs oder Fenstern wird es nie geben.

Neue Fenster macht niemand mehr auf professionellen Seiten auf, weil das bei mobile Devices zu einem neuen Fenster führt, den man als solchen wegen Überlagerung nicht erkennt. Man wird dann allerdings kein "Back" nutzen können.
Zudem ist das Öffenen eines Fensters ein Eingriff in die Userhoheit und damit ein NoGo.

**Comment by mikalehmann** [comment]
Jede Seite macht es heutzutage so, dass Social Media Buttons in einem neuen Tab geöffnet werden. Wieso sollten wir das nicht tun? Wie schon gesagt, werden auf die jetzige Weise die Nutzer von unserer Seite geleitet.

"Neue Fenster macht niemand mehr auf professionellen Seiten auf, weil das bei mobile Devices zu einem neuen Fenster führt, den man als solchen wegen Überlagerung nicht erkennt."
Du meinst Tabs, oder?

Selbst bei Mobilgeräten macht ein neuer Tab mehr Sinn, da dieser beim sofortigen Drücken auf "Back" direkt wieder geschlossen wird und man somit ohne einen neuen Ladevorgang wieder auf unserer Website landet.

**Comment by xwolfde** [comment]
Nein. Nur weil das viele Pfuscher machen, machen wir das nicht.

**Comment by xwolfde** [comment]
http://www.barrierefreies-webdesign.de/knowhow/pop-up-fenster/abschliessende-bemerkungen.html
https://www.usability-tipps.de/info/index.php/links-in-neuem-fenster-offnen/
http://www.media-affin.de/gruende-gegen-target-blank
http://blog.xwolf.de/2014/11/20/theme-piratenkleider-links-in-neuen-fenster-oeffnen/

**Comment by mikalehmann** [comment]
Sorry, aber diese Einstellung ist vollkommen überholt. Mittlerweile ist das Surfen mit Tabs standard, auch im Mobilbereich. Gegen neue Fenster kann ich ja verstehen, aber Tabs sind absolut kein Problem und Fenster öffnet sowieso kein Browser mehr.

**Comment by xwolfde** [comment]
Tja, das sehen allerdings der W3C und die WCAG etwas anders.
Das ist sicher auch eine subjektive Entscheidung. Für mich ist es ein NoGo das Verhalten des Surfers zu bestimmen, indem ich dessen Browser ohne vorherige Warnung und Zustimmung des Users zu einer Aktion leite.

**Comment by Lehmax** [comment]
Denk bitte noch einmal über die Entscheidung nach und überlege dir, ob es sinnvoll ist das Verhalten unserer Website an eine Minderheit anzupassen. Genau das sind nämlich die Nutzer, die wissen wie man Links in einem neuen Tab öffnet.

**Comment by xwolfde** [comment]
Wenn du möchtest, dass ich drüber nachdenke, solltest du sachliche gründe liefern, warum es besser sein soll. Bisher hast du als einzigen "Pro"-Punkt genannt: Weil andere es auch tun.

Und du bist auf keinen der genannten Argumente ernsthaft eingegangen

**Comment by mikalehmann** [comment]
Hab mal ein wenig rumgetestet und bin doch zu dem Schluss gekommen, dass es in diesem Fall unnötig ist. Kann ruhig so bleiben. Case closed, würde ich sagen.
