### ISSUE TITLE
unnötiges Komma

### ISSUE THREAD

**Issue by sebulino** [Piratenpartei/Pirate-Rogue#148]
https://www.piratenpartei.de/partei/landesverbaende/

__Klick auf dein Hoheitsgebiet, um mehr zu erfahren: __
Soweit ich weiss gilt folgendes:
Bei erweitertem Infinitiv kommt vor dem "um" ein Komma, ES SEI DENN er wird nur um ein Wort erweitert.

**Comment by ukcb** [comment]
Check mal die Mailto-Links bei den Landesverbänden auf derselben Seite -> die beginnen mit http:// und enden mit /

**Comment by xwolfde** [comment]
fixed
