### ISSUE TITLE
typo 'en' fehlt und Komma

### ISSUE THREAD

**Issue by sebulino** [Piratenpartei/Pirate-Rogue#151]
https://www.piratenpartei.de/mission/zukunftsliebende/

1.
unten erster Bullet Point dritter Satz:
"Das macht Deutschland nicht nur menschenfreundlicher, sondern bietet Unternehmen ein weiteren, unerreichten und geldwerten Standortvorteil." -> "... bietet Unternehmen einen weiteren..."

2.
2. Bullet Point zweiter Satz:
"Wir ermöglichen jedem Bürger ohne Mehraufwand Zusatzeinkünfte mit seinen Immobilien zu erzielen." -> "... jedem Bürger, ohne Mehraufwand Zusatzeinkünfte..."

3.
4. Bullet point erster Satz:
"Hilfsorganisationen helfen einfacher mehr Spenden zu sammeln" - "... helfen, einfacher mehr..."
4. Buller point zweiter Satz:
"eine neue Art des Spendens und integrieren dies in bestehende" -> "... und integrieren diese in ..."

**Comment by xwolfde** [comment]
fixed
