### ISSUE TITLE
Alte Satzung verlinkt

### ISSUE THREAD

**Issue by sebulino** [Piratenpartei/Pirate-Rogue#152]
in https://www.piratenpartei.de/partei/satzung/ ist die alte Satzung verlinkt
Die Satzung ist nicht in der letzten Version, es kam die Änderung vim BPT17.1 zur Höhe des Mitgliedsbeitrags dazu (http://wiki.piratenpartei.de/wiki/index.php?title=Bundessatzung&diff=2533412&oldid=2501917). 

http://wiki.piratenpartei.de/Satzung

**Comment by xwolfde** [comment]
fixed
