### ISSUE TITLE
Featured-Bereich im Footer

### ISSUE THREAD

**Issue by ukcb** [Piratenpartei/Pirate-Rogue#154]
Wenn kein Bild im Featured-Bereich im Footer angegeben wird, sieht man den Titeltext als alternativen Text. Wenn kein Bild angegeben wird, dann sollte auch kein alternativer Text auftauchen.
Wenn kein Button-Text angegeben wird, sieht man trotzdem einen Button mit Link auf href=""

[Testseite](https://testing.piratenbrandenburg.de/)

**Comment by xwolfde** [comment]
in nächsten version gefixt

**Comment by ukcb** [comment]
Ist es gewollt, dass der ganze Bereich nicht mehr angezeigt wird, wenn kein Bild angegeben wird?
Das verbaut die Möglichkeit an dieser Stelle Text anzuzeigen. Vermutlich war das nicht das Ziel.
