### ISSUE TITLE
Blogroll Artikel

### ISSUE THREAD

**Issue by xwolfde** [Piratenpartei/Pirate-Rogue#156]
Irendwas passt mit der Query nicht.
In der PM Cat werden andere Artikel gezeigt die nicht PM sind.
https://www.piratenpartei.de/presse/mitteilungen/

**Comment by ukcb** [comment]
Gesehen habe ich das auch. Ich dachte, du hättest irgend etwas mit Multi-Kategorien eingebaut. :-)
So mit cat="foo" cat="bar" oder  cat="foo,bar" - kannst ja drüber nachdenken, wenn du eh den Code anfasst.

**Comment by xwolfde** [comment]
Im Beta ist eine Korrektur
