### ISSUE TITLE
Logo im Footer

### ISSUE THREAD

**Issue by ukcb** [Piratenpartei/Pirate-Rogue#164]
Es wäre schön, wenn man ein eigenes Logo im Footer **extra** definieren könnte. Man kann zwar sagen, dass man das eigene Logo verwenden möchte, aber dann wird das Logo des Headers verwendet. Hat man dort ein Kampagnenlogo kleben, hat man keine Chance das Footer-Logo zu ändern. Die Nebenwirkung sieht man z.Z. beim LV Bayern.

**Comment by xwolfde** [comment]
Ist doch vorhanden?

Customizer->Theme Optionen -> Featured-Bereich im Footer

Da kannst du auch ein anderes Logo setzen.  Hab es gerade auf piratenpartei.de auch nochmal gemacht

**Comment by ukcb** [comment]
Da hast du es versteckt. Ich bin hier lang gegangen:

Customizer -> Website-Informationen -> [x] Zeige eigenes Logo im Footer

BTW: Diese Einstellung ändert übrigens nichts, wenn ein Logo über
Customizer->Theme Optionen -> Featured-Bereich im Footer gesetzt ist.
Da hätte ich jetzt das Logo von Customizer->Website-Informationen->Logo erwartet.

Aber gut zu wissen, wo man suchen muss. :-)
