### ISSUE TITLE
Artikel oben behalten

### ISSUE THREAD

**Issue by ukcb** [Piratenpartei/Pirate-Rogue#166]
Ich sehe gerade, dass die Artikel-Einstellung "Artikel oben behalten" z.B. im "Featured-Bereich oben" nicht funktioniert wie erwartet. In [blogroll] wird die Einstellung scheinbar auch nicht berücksichtigt. Kann man da etwas machen? Unter "Letzte Beträge" sieht es ok aus.

**Comment by xwolfde** [comment]
Es ist eigentlich so wie es soll. Bei dem Shortcode Blogroll aber auch bei den featured Artikel und Slidern wird ja ein Tag oder eine Kategorie gewählt. Ein Sticked  ist eine anderes Attribut, welches prinzipiell nur für die normale Blogroll gedacht ist...
