### ISSUE TITLE
Größe der Beitragsbilder

### ISSUE THREAD

**Issue by ukcb** [Piratenpartei/Pirate-Rogue#167]
Ich habe gerade von Piratenkleider auf Pirate-Rogue umgestellt. Die Betragsbilder werden viel zu klein dargestellt, obwohl sie im Original viel größer sind. Ist das ein Problem von WP 4.8 oder von Pirate-Rogue?

[Test1](https://www.piratenbrandenburg.de/2017/06/ausfall-auf-twitter-zusammenfassung/)

Es sieht so aus, als wenn die Breite auf 150px festgelegt wird.

Hier noch ein Beispiel für [eine Seite](https://www.piratenbrandenburg.de/btw2017/) - das sieht auf dem Desktop richtig krass aus.

**Comment by xwolfde** [comment]
Ich vermute, es liegt daran, dass die Bilder eben alt sind und daher nicht in den neuen Bildformaten angelegt wurden, die das Theme mitbringt.
Hol dir doch mal das Plugin 
https://wordpress.org/plugins/regenerate-thumbnails/

**Comment by ukcb** [comment]
Danke, das Plugin hat mir geholfen.
