### ISSUE TITLE
Hintergrundbild ändern für bessere Lesbarkeit

### ISSUE THREAD

**Issue by sebulino** [Piratenpartei/Pirate-Rogue#169]
https://www.piratenpartei.de/aktuelles/

<img width="1259" alt="bildschirmfoto 2017-06-20 um 21 04 03" src="https://user-images.githubusercontent.com/1427176/27350919-0a0082e2-55fc-11e7-9498-52aab3ec548c.png">

**Comment by xwolfde** [comment]
in der nächsten version besser (text-shadow)
