### ISSUE TITLE
Silbentrennung in Überschriften

### ISSUE THREAD

**Issue by jottesjs** [Piratenpartei/Pirate-Rogue#172]
Wie auf Twitter besprochen kurzer Eintrag.

Die Lesbarkeit von Überschriften wird deutlich verbessert, wenn dort keine Silbentrennung stattfindet.

Wenn doch eine Trennung nötig wird, dann nur in Ausnahmefällen, und nicht auf beliebigen Silben, sondern auf geeigneten Wortbestandteilen (Wasser-flugzeug, statt Wasserflug-zeug), so dass der Sinnzusammenhang beim Lesen nicht abbricht.

Im Fließtext ist eine gute Regel, dass auf eine Silbentrennung mindestens 2 Zeilen ohne Trennung folgen. Ansonsten gilt auch hier, dass Trennung vorzugsweise auf Wortbesandteile angewandt werden.

Ich vermute, dass aktuelle automatische Silbentrenner letztere Dinge nicht beherrschen. Eine gute Lösung wäre imho daher, einfach auf die Silbentrennung in Überschriften zu verzichten und den Rest lassen wie es ist.

Grüße, und Danke für Deine Arbeit!

**Comment by xwolfde** [comment]
#171

**Comment by xwolfde** [comment]
in der nächsten Version enthalten
