### ISSUE TITLE
Visitenkarten?

### ISSUE THREAD

**Issue by diesocke** [Piratenpartei/Pirate-Rogue#182]
Unter dem Theme Piratenkleider konnten Visitenkarten genutzt werden. Dies haben wir umfassend getan und dort viele Inhalte abgelegt. Durch den Themewechsel sind die Inhalte nun nicht mehr verfügbar. (Würgaround: Piratenkleider reaktivieren, Inhalte sichern, neu unter Pirate Crew einfügen.) Die URL $DOMAIN/person/$NAME, die ich z.B. in meiner Mail-Signatur habe,  ist nicht verfügbar.

Es wäre toll, wenn diese Funktion abwärtskompatibel nachgebildet werden könnte und die bestehenden Daten/URLs auch im neuen Theme verfügbar wären.

**Comment by xwolfde** [comment]
tut mir leid, das war leider nicht machbar. (Hatte ich schon am Anfang des Projekts durchkaut)
