### ISSUE TITLE
Bei zu langen Überschriften verrutscht Hamburger-Menü

### ISSUE THREAD

**Issue by diesocke** [Piratenpartei/Pirate-Rogue#183]
Bei langen Überschriften (z.B. "Kein tragfähiges Konzept zum Bevölkerungsschutz in Leverkusen") rutscht in der mobilen Ansicht das Hamburger-Menü nach rechts weg, so dass es nicht mehr angezeigt wird. Mit einem Wischer findet man es zwar jenseits des Displays am rechten Rand, aber das ist nicht intuitiv zu finden.

**Comment by xwolfde** [comment]
Wenn man solche langen Überschriften als Seitentitel hat, hat man keinen Titel, sondern einen Satz.
Sorry, das ist ein Bedienerproblem.
