### ISSUE TITLE
Verwendung eines Autors aus Pirate-Crew

### ISSUE THREAD

**Issue by ukcb** [Piratenpartei/Pirate-Rogue#187]
Wäre es machbar, dass bei Verwendung eines Autors aus Pirate-Crew, dieser Autor auch als Autor des Blogbeitrags im Text erscheinen könnte? Das sollte aber optional sein und nicht automatisch.

**Comment by ukcb** [comment]
Nach längerer Überlegung sind wir zu dem Schluss gekommen, dass dieses Verhalten nicht optimal wäre und andere Probleme nach sich ziehen würde.

**Comment by xwolfde** [comment]
Deswegen hab ich es auch nur als optionale Auswahlliste gemacht :P

**Comment by ukcb** [comment]
Ja, hast du. :-) Deine Auswahlliste ändert den Artikelautor aber nicht. Das Plugin https://wordpress.org/plugins/change-author/ kann das - wir verzichten darauf.

PS: Wäre nett, wenn du neue Versionen mit Tags der Version markieren könntest. Danke.

**Comment by xwolfde** [comment]
Wozu mit Tags? Master ist das jeweils letzte Release. Entwicklungsversionen sind immer im Betabranch. Wenn den GitHub Updater nutzt, reicht es, auf den master-Banch zu schauen
