### ISSUE TITLE
Typo in template-parts/footer-feature.php, line 14

### ISSUE THREAD

**Issue by cassandre** [Piratenpartei/Pirate-Rogue#188]
$linkttitle --> $linktitle
Dadurch Undefined-Index-Notice in Z. 39.

**Comment by xwolfde** [comment]
hm... hast du die aktuelle Version? Ich meine den Bug gefixt zu haben, finde aber nicht mehr den Commit wann...
Aktuell ist es korrekt.

**Comment by cassandre** [comment]
Ah, OK, da hatte sich was geändert. Nee, hatte noch 1.1.2
