### ISSUE TITLE
Darstellung von Tabellen

### ISSUE THREAD

**Issue by diesocke** [Piratenpartei/Pirate-Rogue#190]
Unter https://www.piratenpartei-leverkusen.de/mitmachen/piratenhandbuch/unsere-werkzeuge/ wird leider die im Quelltext vorgesehene Tabelle nur unvollständig dargestellt. Unter den Piratenkleidern wurde die Tabelle vollständig dargestellt. Können 7-spaltige Tabellen im Theme überhaupt abgebildet werden? Welche Möglichkeiten bestehen, dies so anzupassen, dass auch die vorgesehenen Kennzeichnungen abgebildet werden?

**Comment by xwolfde** [comment]
Was soll das Theme denn bei überbreiten Tabellen tun?

**Comment by diesocke** [comment]
Ist die Tabelle denn überbreit? Spalte 0 gibt 48pts vor, die Spalten 3-7 jeweils 16. 128 finde ich jetzt nicht so riesig viel, der Text in Spalten 2 und 3 müsste sich halt mit dem Platz  begnügen, der noch da ist. Je nach Auflösung sollte das zunehmend mehr werden, oder geh ich da fehl? Was wäre denn die maximale Breite des Inhalts?

**Comment by xwolfde** [comment]
Äh, naja, du hattest doch gesagt, dass etwas fehlt?  Ich kann das bei obigen Beispiele nicht sehen.

**Comment by xwolfde** [comment]
Jetzt wollte ich es mir nochmal anschauen, da ist die Webseite weg... :(

**Comment by diesocke** [comment]
Dass die Seite weg war, lag am Hosting der NRW-Piraten, das kurz vor Weihnachten ausfiel. Ist wieder da: https://www.piratenpartei-leverkusen.de/mitmachen/piratenhandbuch/unsere-werkzeuge/

**Comment by xwolfde** [comment]
Ich raff es nicht. Was fehlt denn jetzt bei der Table? Das sieht doch alles richtig aus?

**Comment by diesocke** [comment]
![Desktop-Modus (Smartphone)](https://sockenseite.de/wordpress/wp-content/uploads/2017/12/Screenshot_20171229-171321-2.png)

![Smartphone-Modus](https://sockenseite.de/wordpress/wp-content/uploads/2017/12/Screenshot_20171229-171329.png)

Dass die Texte bei kleinem Bildschirm zerschießen, ist ja verständlich, dass aber die bei kleinem Screen dargestellten Tabellenspalten im Desktop-Modus verschwinden, ist verwunderlich.

**Comment by xwolfde** [comment]
ah jetzt... Hm... och schau mal. Einstweilen wechsele doch auf das Template "Seite mit voller Breite für den Inhalt", dann ist wenigstens etwas da.

Ansonsten könntest du die Häckchen ab der 4. Spalte ja auch nicht als Spalten machen, sondern als Text-Absatz unter der 2. Spalte

**Comment by xwolfde** [comment]
Eine Lösung gibt es gleich im Git
