### ISSUE TITLE
Aenderung des Slider-Stils liefert "Ungültiger Wert." zurueck

### ISSUE THREAD

**Issue by Fenian** [Piratenpartei/Pirate-Rogue#195]
In customizer.php versteckt sich ein kleiner Schreibfehler:

In Zeile 703 muss es wohl
`sanitize_callback' 	=> 'pirate_rogue_sanitize_sliderstyle',`
anstelle von
`sanitize_callback' 	=> 'pirate_rogues_sanitize_sliderstyle',`
heissen

**Comment by xwolfde** [comment]
Hast recht. Danke fürs finden&melden. Update ist im Master
