### ISSUE TITLE
Color-Settings

### ISSUE THREAD

**Issue by xwolfde** [Piratenpartei/Pirate-Rogue#197]
Neue Funktion im Customizer:
Farben der Bereiche (Kopf, Body, Fußteil, Overlay), der Überschriften und weitere sollen durch eigene Auswahl aus einem Set an vorgegebenen Farben überschreibbar sein.

**Comment by xwolfde** [comment]
Im Beta ist eine erste testfähige Version.
Zu sehen auch hier: http://spielwiese.pirate-rogue.de/textelemente/ 
Ich bin noch unschlüssig ob ich die Farbe der Buttons und hervorgehobenen Bedienelemente auch noch änderbar machen soll.

**Comment by xwolfde** [comment]
Tabellen und hr's müssen noch verbessert werden

**Comment by xwolfde** [comment]
released in 1.2.0

**Comment by xwolfde** [comment]
Kategorie-Tag: Hintergrund bei wechselnder Linkfarbe checken in einem Artikel
Tables: Noch nicht gut. besser Farben auswählbar machen

**Comment by xwolfde** [comment]
-Noch Problem bei kleinen Auflösungen mit dem Kopfteil-
ab 1.2.1 behoben

**Comment by diesocke** [comment]
Es wäre BTW hilfreich, wenn die per default gesetzte Farbe bereits angezeigt wird.

**Comment by xwolfde** [comment]
Kommt gleich in Git
