### ISSUE TITLE
Bestimmte Klasse von Bullets bei UL ausnehmen

### ISSUE THREAD

**Issue by diesocke** [Piratenpartei/Pirate-Rogue#198]
Ich würde gerne in Pirate Rogue eine bestimmte Klasse von den bei <ul> gesetzten vorangestellten Bullets ausnehmen. 

Wir nutzen das Plug-in TOC+, um automatisch Inhaltsverzeichnisse komplexer Seiten anzuzeigen. Da im Plug-in die Inhalte als UL dargestellt werden, ergänzt das Theme entsprechende Bullets. Dies sieht im konkreten Fall (siehe Screenshot) aber unschön aus, deswegen ich das gerne mit ...
```
not (.toc_list)
```
...  unterbinden würde.

Wo in der style.css finde ich die entsprechende Formatierung, die ich im Child-Theme anpassen könnte?

![Screenshot](https://sockenseite.de/wordpress/wp-content/uploads/2017/12/Screenshot_20171231-153611.png)

**Comment by xwolfde** [comment]
Dafür gibt es die Klasse "default":
&lt;ul class="default"&gt; .. 

Siehe http://www.pirate-rogue.de/text-styles/listen/

Ich hab aber gerade gesehen, dass da die Margins noch falsch waren. Im Beta-Branch hab ich es schon korrigiert. Meine pirate-rogue.de läuft auf der Beta.

Die style.css kannst du nicht  bearbeiten, da die aus SASS compiliert wurde. Die Anweisungen für die Listen findest du in der SASS-Datei https://github.com/Piratenpartei/Pirate-Rogue/blob/master/css/sass/elements/_lists.scss 

Zur Compilierung der SASS-Files wird folgende Einstellung verwendet: 

Input-dir: /css/sass
Output-Dir: /css
Parameter für den SASS-Compiler: --style compressed  --sourcemap=none

**Comment by diesocke** [comment]
Ich würde ohnehin nur im Childtheme in der style.css fummeln. Dafür bräuchte ich halt die entsprechenden Anweisungen, die ich darin "überschreiben" müsste. Das wären also die in der _lists.scss?

**Comment by xwolfde** [comment]
jupp. Im wesentlichen musst du das machen, was unter der .default-Angabe steht. Ich mach jetzt gleich ein git merge: Hab gerade die Übersetzung aktualisiert und denke die neuen Features und Bugfixes können in den Master.

SASS anzuschauen würde aber trotzdem nicht schaden. Es macht wirklich viele DInge viel leichter.
