### ISSUE TITLE
Darstellung Slider ohne Javascript

### ISSUE THREAD

**Issue by ukcb** [Piratenpartei/Pirate-Rogue#204]
Wenn der Slider aktiviert und Javascript deaktiviert ist, hat man ein riesen "Loch" oben auf der Seite (siehe Screenshot). Kann man da was machen, damit das "Loch" verschwindet? 

![piratenpartei deutschland](https://user-images.githubusercontent.com/22983914/34999061-f8a65b40-fae0-11e7-8cb7-771f2456e2d2.png)

**Comment by xwolfde** [comment]
Ja, wäre nett. Wenn ich mal Zeit hab mich um die 0.5% der betreffenden User zu kümmern, denke ich dran.

**Comment by ukcb** [comment]
Es geht nicht nur um die Javascript-Verweigerer. Es betrifft auch Serverbetreiber, die in ihrer Content-Security-Policy in der script-src Directive nicht 'unsafe-inline' angeben wollen um einen Status A+ zu erreichen. Das wäre ein Pluspunkt für das Theme.

**Comment by xwolfde** [comment]
Bei Slider mit dynamisch wechselnden Content kommst du leider nicht ohne Inline-Anweisungen aus. Denn die Alternative wäre, dass du vom CMS je nach Contentwechsel eine neue JS-Datei ablegen müsstest; Die könnte man ggf. via Crontabs erzeugen oder beim Erzeugen des neuen Content vom Autoren. Was aber nicht unbedingt trivial wäre, da man dann wiederum die Preview nicht zeitgleich haben könnte.
Eine andere Alternative wäre die, dass du das JS dynamisch beim Aufruf erzeugst. Dies verursacht dann aber eine Verschlechterung der Performance.
Beide Alternativen sind also problematisch oder führen zu größeren Nachteilen.
Eine höhere Sicherheit hast du damit nicht erreicht, weil du das Problem nur woanders hin verlagerst.

**Comment by xwolfde** [comment]
In der 1.3.0 drin. Aktuell im Beta
