### ISSUE TITLE
Klappmenüs bei kleiner Schriftgröße schlecht bedienbar

### ISSUE THREAD

**Issue by JanRei** [Piratenpartei/Pirate-Rogue#206]
Wenn im Browser eine kleine Schriftgröße eingestellt ist, sind die ausklappenden Menüs schlecht bedienbar. Dann rutscht der Inhaltsbereich etwas nach oben. Beim Überfahren der Lücke (zwischen Hauptmenüpunkt und Untermenü) wird das Menü geschlossen, womit dieses nicht erreichbar ist.

![grafik](https://user-images.githubusercontent.com/2790261/35780333-ef9c5a56-09d9-11e8-9865-2563101f67e2.png)

_Pirate Rogue 1.2.10, Firefox 58_

**Comment by jm009** [comment]
Ich bin derjenige, der den Screenshot gemacht hat.
Die Vermutung, das liege an einer kleineren Schriftart kann ich nicht bestätigen.
Ich habe ein aktuelles Debian (Stretch 9.3).
Zoom-Faktor in Firefox (52.6.0 64bit) ist 100%.
Schrifteinstellungen sind

Proportianal: Serif 12
Serif: serif
Sans Serif: sans-serif
Feste Breite: monospace 12
Mindestschriftgröße: keine

**Comment by xwolfde** [comment]
@jm009 Könntest du bitte hier mal testen, ob das Problem noch auftritt: http://www.pirate-rogue.de/blog/ ?

**Comment by JanRei** [comment]
Also für mich ist das Problem dort weiterhin reproduzierbar.

**Comment by xwolfde** [comment]
Für mich nicht - weder auf Opera, FF, Edge oder Chrome unter Windows oder Opera, FF, Chrome unter Mac.
Sorry, aber da bin ich raus - wenn ich es nicht nachstellen kann, kann ich es auch nicht patchen.

**Comment by JanRei** [comment]
Bei mir tritt das Problem in Firefox direkt nach Änderung der Schriftgröße von 16 auf 12 auf. In Chrome sieht es genau so aus nach Änderung von "Mittel (Empfohlen)" auf "Klein".

Vergrößerung/Zoom hat bei mir keinen Einfluss.

**Comment by xwolfde** [comment]
aaaaah... das die Schriftgröße verändert wurde, hab ich oben ganz überlesen. Ok, das ist ein Anhaltspunkt.

**Comment by jm009** [comment]
a) Ich verweise auf meinen Kommentar https://github.com/Piratenpartei/Pirate-Rogue/issues/206#issuecomment-364631300 - ich habe die Schriftgröße **nicht** verändert (!)

b) Das Problem tritt noch auf, auf http://www.pirate-rogue.de/blog/ , auf piratenpartei.de und auf piratenpartei-bw.de

c) Sind Klappmenüs in Zeiten von Touchscreens noch in?

**Comment by xwolfde** [comment]
naja, dann muss ich sagen: Sorry, siehe mein Comment oben.

**Comment by JanRei** [comment]
Das von mir berichtete Problem mit der Schriftgröße besteht ja in jedem Fall. Es wäre nett, wenn du dir das mal ansehen könntest. 

Vielleicht hilft dies auch bei jm009s Problem. Ein anderen Anhaltspunkt scheint es momentan nicht zu geben...

**Comment by jm009** [comment]
Ich habe heute gemerkt, dass das gleiche Problem (Spalt zwischen Menüpunkt und Klappmenü) auch auf der Webseite https://www.provieh.de/ auftritt.
Daraufhin habe ich hier nochmal gelesen, dass JanRei schreibt, dass bei ihm das Problem auftritt, wenn er die Schriftgröße von 16 auf 12 ändert.
In der Tat, wenn ich die Schriftgröße in meinem Firefox von 12 auf 16 ändere, verschwindet das Problem (Einstellungen->Inhalt->Standard-Schriftart->Größe).

**Comment by xwolfde** [comment]
In der 1.3.0 gefixt. Aktuell im Beta
