### ISSUE TITLE
WP GDPR Compliance

### ISSUE THREAD

**Issue by ukcb** [Piratenpartei/Pirate-Rogue#210]
Wenn man das Plugin https://wordpress.org/plugins/wp-gdpr-compliance/ benutzt, wird der Code

```
<p class="wpgdprc-checkbox">
<label>
<input type="checkbox" name="wpgdprc" id="wpgdprc" value="1" />
Mit der Nutzung dieses Formulars erklärst du dich mit der Speicherung
und Verarbeitung deiner Daten durch diese Website einverstanden. 
<abbr class="required" title="required">*</abbr>
</label>
</p>
```
bei den Kommentarformularen von Wordpress leider nicht angezeigt (display none).

Kannst du da bitte etwas machen?

**Comment by ukcb** [comment]
Könnte man nicht gleich eine Checkbox zum Datenschutz in das Theme einbauen? Das braucht wahrscheinlich jeder in Zukunft.

**Comment by xwolfde** [comment]
Bei dem üblichen Formular-Plugin, wie CF7 hast du alle Möglichkeiten der Welt, das HTML des Formulars selbst zu gestalten. Du musst es sogar. Was CF7 oder das das Formularplugin da sonst macht, ist Sache des Plugins.
Und bei dem Kommentarformular ist im Theme bereits ein Eingabefeld vorhanden, um beliebigen Text voranzustellen.
Auf der Bundeswebsite haben wir den Text der dort verwendet wurde damals mit dem DSB abgeklärt, das ist also den Regeln des Datenschutzes schon genüge.

**Comment by ukcb** [comment]
In CF7 gibt es das Problem nicht. Im Supportforum von GDPR Compliance sieht man, dass andere Leute mit anderen Themes ähnliche Probleme haben.  Auf unserem Landesblog (BB) behelfe ich mir mit `#commentform p.wpgdprc-checkbox label {display:inline !important;}` das macht das Feld sichtbar. 
Die Sache mit dem vorangestellten Text ist nicht verkehrt. Allerdings vermisse ich an der Stelle die Interaktion. Dem Text auf der Bundeswebsite entnehme ich z.B. keinen Hinweis auf eine Einwilligung zur Speicherung und Verarbeitung von Daten nach DSGVO Art: 6/7. 
Wenn das Plugin GDPR Compliance mit anderen Themes funktioniert (zB Piratenkleider) dann sehe ich das Problem auf Seiten des Themes und nicht beim Plugin.

**Comment by xwolfde** [comment]
In der kommenden 1.3.1 gefixt.
