### ISSUE TITLE
Navigation teilweise überdeckt

### ISSUE THREAD

**Issue by ukcb** [Piratenpartei/Pirate-Rogue#216]
Unter Umständen wird die Navigation teilweise überdeckt.

class="meta-main-wrap" liegt mit z-index: 100; über id="site-branding" mit z-index: 21;

Siehe Screenshot

![piratenpartei deutschland 20180630-122549](https://user-images.githubusercontent.com/22983914/42124376-d35b97f8-7c61-11e8-95a4-818067870b21.png)

**Comment by xwolfde** [comment]
fixed

**Comment by ukcb** [comment]
Ist der Fix schon commited? Ich sehe keine Änderung in v1.4.5.

**Comment by xwolfde** [comment]
Bei meinen Testcases tritt der Bug nicht auf. Ich kann das obige Bild nicht nachstellen. 
Geb mir mehr Infos.  URL?

**Comment by ukcb** [comment]
Ich habe das auf Android/Firefox und sonst mit Firefox (oder Palemoon etc.) mit maximal Zoom. URL ist direkt die Startseite hier: https://www.piratenbrandenburg.de/
Hab mal denn z-index für site-branding nur im Firefox testweise auf 1000 gesetzt, dann sieht es normal aus.

![20190519-190650](https://user-images.githubusercontent.com/22983914/57985590-4f799180-7a6a-11e9-85e6-6fc3ce33e5b6.png)

![Unbenannt](https://user-images.githubusercontent.com/22983914/57985981-6373c200-7a6f-11e9-91fe-112e4b400c4a.png)

**Comment by xwolfde** [comment]
![Screenshot_20190520-133822](https://user-images.githubusercontent.com/1070669/58019217-4be71880-7b05-11e9-8806-a5d7a7e0e3c6.png)
![Screenshot_20190520-133843](https://user-images.githubusercontent.com/1070669/58019229-543f5380-7b05-11e9-984d-19caed7e7acf.png)

Firefox android. 
Die einzige Überlagerung kommt von dem zu langen copyright

**Comment by ukcb** [comment]
Ok, vielleicht war meine Fehlerbeschreibung zu kurz oder missverständlich. Es geht nicht um den Slider. Bitte mal runterscrollen zu den Artikeln mit den vergrößerten Bildern. Dann solltest du den Effekt sehen.

**Comment by xwolfde** [comment]
Aaah, jetzt hab ich es kapiert. Sorry für den Braindelay.

Ist in der neuen Version gefixt.

**Comment by ukcb** [comment]
Danke, funktioniert. :-)
