### ISSUE TITLE
Trennstrich zwischen Artikelkategorien möglicherweise schlecht erkennbar

### ISSUE THREAD

**Issue by JanRei** [Piratenpartei/Pirate-Rogue#221]
Der Trennstrich zwischen Artikelkategorien ist möglicherweise schlecht erkennbar:
![grafik](https://user-images.githubusercontent.com/2790261/53004769-1f523080-3432-11e9-8c8c-2a92ed62b3b5.png)

Ich schlage vor, den Strich vor den Kategorielink zu setzen oder einfach weg zu lassen.

**Comment by xwolfde** [comment]
Das ist ein Bug. Der sollte gar keine BG Col haben. Dann ist der auch gut erkennbar

**Comment by xwolfde** [comment]
im Dev
