### ISSUE TITLE
Why isn't this theme in the wordpress theme directory?

### ISSUE THREAD

**Issue by AvverbioPronome** [Piratenpartei/Pirate-Rogue#232]
I assume there is a reason. Please share it with me :D 

Thanks.

**Comment by xwolfde** [comment]
As we made the theme in 2017, we had to create the theme in very short time.
Therfor we didnt wanted to lose the time to fight with old school CVS repositories and an outdated theme tester reviews :)

People who are using the github updater plugin can easely get the theme from github also instead only from wptheme directory.
