### ISSUE TITLE
Inhalt von Titel der Webseite und Untertitel ausgeblendet

### ISSUE THREAD

**Issue by crydotsnake** [Piratenpartei/Pirate-Rogue#234]
Wenn man ein Logo hochlädt, wird der Inhalt von Titel der Webseite und Untertitel ausgeblendet.
Wenn man das Logo wieder entfernt, bleiben die zwei Felder trotzdem ausgeblendet.

Mit Logo:

![Bildschirmfoto 2021-02-13 um 23 07 59](https://user-images.githubusercontent.com/39345336/107862882-52c4cb80-6e50-11eb-944e-3acc88f4eb0b.png)

Ohne Logo:

![Bildschirmfoto 2021-02-13 um 23 08 56](https://user-images.githubusercontent.com/39345336/107862908-76881180-6e50-11eb-8729-24f5344b7ea4.png)

**Comment by xwolfde** [comment]
Ja, stimmt. Ist ein Bug.

Ich mach allerdings mangels Zeit nichts mehr an dem Theme.
Es ist von 2017 und war nur als Übergangslösung für den BTW2017 gedacht.
Es ist daher inzwischen technisch völlig überaltet. Sucht euch am Besten ein neues Theme, welches auch für das kommende WP5.7 geeignet ist.

**Comment by crydotsnake** [comment]
Verstehe. 

Ich würde denn Bug gerne Beheben. Außerdem habe ich vor, die Funktionen des Child Themes in das Rogue Theme zu Integrieren.

**Comment by xwolfde** [comment]
Das wäre natürlich super.

Ich glaub nur, dass es leichter & stressfreier wäre, ein neues Theme sauber  neu zu starten, als an dem weiter rumzupatchen.

**Comment by crydotsnake** [comment]
Verstehe.. müsste ich mir erst Gedanken drüber machen, wie ich da am besten anfange.
