### ISSUE TITLE
Kursivstellung aus Artikel-Excerpt wird auf Startseite vererbt

### ISSUE THREAD

**Issue by diesocke** [Piratenpartei/Pirate-Rogue#239]
Wenn im auf der Startseite angezeigten Excerpt des Artikels eine Kursiv-Formatierung am Ende des Ausschnitts aktiv ist, wird dieses bei der Darstellung der restlichen Seite vererbt.
![image](https://user-images.githubusercontent.com/7019947/132388880-817d66bd-f8b2-46bb-b566-cab88b45b14b.png)

Wird dies im Artikel entfernt, hört auch die Kursivstellung auf. Für andere die Darstellung beeinflussende Formatierungen hab ich dies nicht getestet.
![image](https://user-images.githubusercontent.com/7019947/132388976-1fb2043f-8c6b-41f2-aa57-8ff9aba11a1b.png)

**Comment by xwolfde** [comment]
Ja, das stimmt. 
Problem ist/war: Es war unter bestimmten Umständen gewünscht, dass man im Excerpt doch HTML machen kann.
Normalerweise würde man alles HTML da löschen. Wurde deswegen aber nicht.
Nun ist es also erlaubt, dass man da HTML macht. Wenn dieses aber kaputt ist (u.a. auch weil der Excerpt zu lang ist und daher gekürzt wird), dann kommt es zu dem Fehler.

Lösung 1: Kein HTML erlauben, dieses automatisch wegmachen.  
Lösung 2: Vorsichtig sein.

Damals hat man sich für Lösung 2 entschieden.
