### ISSUE TITLE
Zu lange Strings, z.B. Links, führen zu Verkleinerung des Contents

### ISSUE THREAD

**Issue by diesocke** [Piratenpartei/Pirate-Rogue#243]
Wenn zu lange nicht umbrochene Zeichenfolgen in einem Beitrag enthalten sind (z.B. bei Links), führt dies v.a. in der mobilen Ansicht zu einer Verkleinerung des Contents, der dadurch schlechter lesbar wird.

Würgaround: absichtliche Umbrüche in URLs einzufügen, Shortener zu verwenden, Begriffe verlinken statt komplette URL im Artikel zu verwenden. Ist alles möglich, aber unschön, wenn z.B. Pressemitteilungen adäquat dokumentiert werden sollen.

Gibt es eine Option, bei der das Theme zu lange Zeichenfolgen automatisch umbricht?

**Comment by xwolfde** [comment]
Im CSS im Kontext
`.entry-content p {}`

ein 
`word-wrap: break-word;`
ergänzen.
Das bricht allerdings ohne Bindestriche um.

Alternative ginge auch / wäre moderner: 
`hyphens: auto;`

Aber das würde ein Bindestrich ergänzen, den ein unbedarfter Leser dann mit abtippen würde, weil er ihn nicht von einem echten Bindestrich in der URL unterschieden kann.

Besser ggf. so:

```sass
.entry-content p {
  hypens: normal;

  a {
   word-break: break-word;
   hyphens: none;
  }
}
```

Ohne SASS für Eingabe über Custom CSS im Optimizer:

```
.entry-content p {  hypens: normal; }
.entry-content p a {  hypens: none; word-break: break-word; }
```


Noch besser aber: Aktuelle und nicht veraltetete analogbasierte Pressearbeit ;)

**Comment by diesocke** [comment]
Thx.

**Comment by xwolfde** [comment]
In der nächstenVersion im Theme eingebaut
