### ISSUE TITLE
Farbe Hauptnavigation Text

### ISSUE THREAD

**Issue by patrickschiffer** [Piratenpartei/Pirate-Rogue#3]
Farbton: #672082

**Comment by xwolfde** [comment]
Hab mal die Farbe gesetzt. Sieht aber zusammen mit der gesetzten lila farbe bei Social media und Overlay Icons nicht so dolle aus.
![screenshot-menu-color-lila](https://cloud.githubusercontent.com/assets/1070669/23572333/b01c5cde-006e-11e7-863a-b0baa4d6797e.jpg)

ich würde es da lieber auf die Default Textfarbe lassen.

![screenshot-menu-color-default](https://cloud.githubusercontent.com/assets/1070669/23572341/b51cb03a-006e-11e7-98c3-02395a1462e0.jpg)

**Comment by xwolfde** [comment]
(Hintergrundfarbe bei den Kategorien ist bei den Screenshots noch nicht gesetzt; Davon nicht ablenken lassen)

**Comment by patrickschiffer** [comment]
Ja, ich meinte auch nur die Hintergrundfarbe bei den Kategorien. Schwarze Navi gefällt mir auch besser.

**Comment by xwolfde** [comment]
ok
