### ISSUE TITLE
Section Featured oben

### ISSUE THREAD

**Issue by ukcb** [Piratenpartei/Pirate-Rogue#48]
Bei "Section Featured oben" überdecken die Kategorie-Tags den Titel.

Testseite: https://testing.piratenbrandenburg.de/
Browser: FF 52.0.1

Nachtrag an dieser Stelle: Die Überschrift für den ganzen Abschnitt "Section Featured oben" ist je nach Skalierung nur teilweise oder gar nicht mehr zu sehen.

**Comment by xwolfde** [comment]
Das passiert, wenn der Beitrag kein Artikelbild hat und auch kein Ersatz-Artikelbild definiert wurde.
Bitte einfach eins von beiden definieren.

**Comment by ukcb** [comment]
Ok, ein Artikelbild fixt die Anzeige der Kategorie-Tags. Das Problem mit der Sichtbarkeit der
Überschrift _`(<h3` class="front-section-title">Section Featured oben <span>...)`_ bei Skalierung bleibt.
