### ISSUE TITLE
Frage zu Visitenkarten

### ISSUE THREAD

**Issue by ukcb** [Piratenpartei/Pirate-Rogue#49]
Kann man die Visitenkarten aus den Piratenkleidern irgendwie retten also quasi einfach migrieren?
Nach der Umstellung gibt es unschöne Seiten mit diesen shorttags [person cat="blub" format="bigtable"]
Wäre schön wenn man an der Stelle Handarbeit vermeiden könnte! :-)

**Comment by xwolfde** [comment]
Es gibt hierzu nun ein eigenes neues Plugin: Pirate-Crew (https://github.com/Piratenpartei/Pirate-Crew) 
Leider kann das nicht ohne sehr viel Verrenkungen übernommen werden ..
Hab ich schon versucht. Hat jedoch den negativen Nebeneffekt, dass dann bei der Pflege der neuen Daten zu Inkompatibilitäten zu dem AWSM Plugin führt, welches als Grundlage zu Pirate-CRew verwendet wird.
