### ISSUE TITLE
Background color für Blöcke

### ISSUE THREAD

**Issue by musikpirat** [Piratenpartei/Pirate-Rogue#50]
Bitte eine Möglichkeit einfügen, Text-Blöcke (z.B. nach Kategorien) mit einem dezenten farblichen Hintergrund abzuheben.

**Comment by xwolfde** [comment]
Hier gibt es das schon (runterscrollen für farbige Hintergründe)
http://www.pirate-rogue.de/tests/theme-shortcodes/shortcodes-fuer-boxen/

**Comment by xwolfde** [comment]
Um den Content eines ganzes Beitrags farbig zu machen, kann man alternativ über Custom CSS folgendes machen:
.single-post .entry-content { background: #eee; }

**Comment by xwolfde** [comment]
@musikpirat: Reichte dir diese Lösung? (Dann mach ich den Issue zu)
