### ISSUE TITLE
Klickfläche im HH-Menü

### ISSUE THREAD

**Issue by ukcb** [Piratenpartei/Pirate-Rogue#53]
Die interaktive Fläche zur Ansicht der Untermenüs (rechte Seite button.dropdown-toggle) ist zu klein und zu weit links. Mit dem Handy ist eine Navigation nervig, wenn man auf den Umschalter tippt und die Seite des angezeigten Menüpunktes angesteuert wird, statt dass das Menü auf- oder zugeklappt wird.

**Comment by xwolfde** [comment]
Hm... ich sehe was du meinst. Wenn ich allerdings den Clickbereich für den Opener größer mache, geht dies zu lasten des Platzes des Menupunktes...

**Comment by ukcb** [comment]
Die Klickfläche nach rechts ausdehnen dürfte den Platz für den Menüpunkt nicht verkleinern (die Höhe ist ja bereits auf maximal).

**Comment by xwolfde** [comment]
Bei einer AUflösung zu 760 Pixel Breite hab ich da nichts mehr auszudehnen...?

**Comment by ukcb** [comment]
siehe Screenshot, ich sehe da noch Platz auf der rechten Seite

![abstand](https://cloud.githubusercontent.com/assets/22983914/24413067/a02623bc-13da-11e7-9cfb-c36884b8e759.jpg)

**Comment by xwolfde** [comment]
ah, ok, das ist ein Bug

**Comment by xwolfde** [comment]
in der nächsten version repariert
