### ISSUE TITLE
Bei Suche ohne Treffer kein Abstand zwischen Header und Inhalt

### ISSUE THREAD

**Issue by JanRei** [Piratenpartei/Pirate-Rogue#58]
Wird bei einer Suche nichts gefunden, gibt es keinen Abstand zwischen Header- und Inhaltsbereich:

![image](https://cloud.githubusercontent.com/assets/2790261/24453970/31da090e-148a-11e7-910d-7fd09d0beb28.png)

**Comment by xwolfde** [comment]
Ist das schon die Version von gestern abend? Bitte mal schauen ob es die 1.0.21 ist. An der Stelle hab ich gestern was gefixt.

**Comment by JanRei** [comment]
Ja, es ist Version 1.0.21.

**Comment by xwolfde** [comment]
Kacke, dann hab ich gestern was an der Stelle kaputt gemacht

**Comment by xwolfde** [comment]
In der nächsten version gefixt
