### ISSUE TITLE
Überlappende Kategorie-Links Featured-Bereich oben

### ISSUE THREAD

**Issue by ghost** [Piratenpartei/Pirate-Rogue#60]
Beim Einstellen einer Kategorie im Featured-Bereich oben kommt es zur Überlappung der Überschrift mit den Kategorie-Links. Ist das ein Bug?

![featured-bereich-oben-kategorielinks](https://cloud.githubusercontent.com/assets/6454734/24675237/b17a1c0a-197e-11e7-9fcd-285c40bf8373.png)

**Comment by xwolfde** [comment]
Jein. Das passiert, wenn der Artikel kein eigenes Artikelbild hat und auch kein Ersatz-Artikelbild definiert wurde. Eines von beiden machen, dann geht es.

**Comment by ghost** [comment]
Danke für die schnelle Antwort.
