### ISSUE TITLE
Fehlender Content

### ISSUE THREAD

**Issue by ukcb** [Piratenpartei/Pirate-Rogue#75]
Habe den aktuellen master installiert. Seit dem letzten Update scheint einiges kaputt gegangen zu sein.
Bei Section Featured oben sehe ich rechts nur Bilder und Linien. Section Featured unten sieht auch seltsam aus, siehe selbst https://testing.piratenbrandenburg.de/ in der letzten Reihe sind z.B. 2 Artikel die kann man nicht anklicken

War das der Grog? :-)

**Comment by xwolfde** [comment]
Huch

**Comment by xwolfde** [comment]
ah, fehler gefunden. wird gleich behoben

**Comment by xwolfde** [comment]
Im nächsten Update gefixt.
(War: Die Überschrift sollte weg, wenn man auf der Starteseite (als statische Seite) ist. leider hat er nun die Überschriften auch bei der Blogroll weggenommen, wenn diese als Startseite definiert war)
