### ISSUE TITLE
Burgermenü zeigt untersten Punkt im Firefox nicht richtig an

### ISSUE THREAD

**Issue by mikalehmann** [Piratenpartei/Pirate-Rogue#92]
So sieht's im Firefox aus:
![firefox](https://cloud.githubusercontent.com/assets/8298953/25741437/2a65968e-318b-11e7-8b53-f7ac04bba5ff.PNG)

Und so bei Chrome:
![chrome](https://cloud.githubusercontent.com/assets/8298953/25741436/2a6516c8-318b-11e7-85e1-55370da070b1.PNG)

In beiden Fällen habe ich komplett nach unten gescrollt.
Im oberen Fall sieht es noch schlimmer aus, weil die Wordpress-Leiste am oberen Rand der Seite zusätzlich Platz wegnimmt. Auch wenn man nicht eingeloggt ist scheint bei Firefox das Menü nicht komplett angezeigt zu werden.

Browser sind beide auf der neusten Version und Bildschirmgröße ist 2560×1440, falls das irgendwie relevant ist. OS ist Windows 10, scaling auf 100%.

**Comment by xwolfde** [comment]
Ja, hab ich auch schon gesehen ... Ich vermute einen Zusammenhang mit dem Offset von der WP-Leiste bei angemeldeten Personen. Muss ich nachgehen.

**Comment by xwolfde** [comment]
fixed
