### ISSUE TITLE
"Leeres" Bild im Fußbereich

### ISSUE THREAD

**Issue by JanRei** [Piratenpartei/Pirate-Rogue#97]
Standardmäßig wird ein "leeres" Bild im Fußbereich angezeigt, was etwas seltsam aussieht. Man kann dies loswerden, indem man ein Bild festlegt und dann wieder entfernt.

![image](https://cloud.githubusercontent.com/assets/2790261/25774092/a79c204c-3289-11e7-99e2-e1387c29d88f.png)

Version: 1.0.48

**Comment by xwolfde** [comment]
im nächsten update behoben
